// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"github.com/facebook/ent/dialect/sql"
	"github.com/facebook/ent/dialect/sql/sqlgraph"
	"github.com/facebook/ent/schema/field"
	"github.com/team06/app/ent/diagnosis"
	"github.com/team06/app/ent/doctor"
	"github.com/team06/app/ent/predicate"
)

// DiagnosisUpdate is the builder for updating Diagnosis entities.
type DiagnosisUpdate struct {
	config
	hooks    []Hook
	mutation *DiagnosisMutation
}

// Where adds a new predicate for the DiagnosisUpdate builder.
func (du *DiagnosisUpdate) Where(ps ...predicate.Diagnosis) *DiagnosisUpdate {
	du.mutation.predicates = append(du.mutation.predicates, ps...)
	return du
}

// AddDiagnosiIDs adds the "diagnosis" edge to the Doctor entity by IDs.
func (du *DiagnosisUpdate) AddDiagnosiIDs(ids ...int) *DiagnosisUpdate {
	du.mutation.AddDiagnosiIDs(ids...)
	return du
}

// AddDiagnosis adds the "diagnosis" edges to the Doctor entity.
func (du *DiagnosisUpdate) AddDiagnosis(d ...*Doctor) *DiagnosisUpdate {
	ids := make([]int, len(d))
	for i := range d {
		ids[i] = d[i].ID
	}
	return du.AddDiagnosiIDs(ids...)
}

// Mutation returns the DiagnosisMutation object of the builder.
func (du *DiagnosisUpdate) Mutation() *DiagnosisMutation {
	return du.mutation
}

// ClearDiagnosis clears all "diagnosis" edges to the Doctor entity.
func (du *DiagnosisUpdate) ClearDiagnosis() *DiagnosisUpdate {
	du.mutation.ClearDiagnosis()
	return du
}

// RemoveDiagnosiIDs removes the "diagnosis" edge to Doctor entities by IDs.
func (du *DiagnosisUpdate) RemoveDiagnosiIDs(ids ...int) *DiagnosisUpdate {
	du.mutation.RemoveDiagnosiIDs(ids...)
	return du
}

// RemoveDiagnosis removes "diagnosis" edges to Doctor entities.
func (du *DiagnosisUpdate) RemoveDiagnosis(d ...*Doctor) *DiagnosisUpdate {
	ids := make([]int, len(d))
	for i := range d {
		ids[i] = d[i].ID
	}
	return du.RemoveDiagnosiIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (du *DiagnosisUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(du.hooks) == 0 {
		affected, err = du.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*DiagnosisMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			du.mutation = mutation
			affected, err = du.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(du.hooks) - 1; i >= 0; i-- {
			mut = du.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, du.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (du *DiagnosisUpdate) SaveX(ctx context.Context) int {
	affected, err := du.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (du *DiagnosisUpdate) Exec(ctx context.Context) error {
	_, err := du.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (du *DiagnosisUpdate) ExecX(ctx context.Context) {
	if err := du.Exec(ctx); err != nil {
		panic(err)
	}
}

func (du *DiagnosisUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   diagnosis.Table,
			Columns: diagnosis.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: diagnosis.FieldID,
			},
		},
	}
	if ps := du.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if du.mutation.DiagnosisCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   diagnosis.DiagnosisTable,
			Columns: diagnosis.DiagnosisPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: doctor.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := du.mutation.RemovedDiagnosisIDs(); len(nodes) > 0 && !du.mutation.DiagnosisCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   diagnosis.DiagnosisTable,
			Columns: diagnosis.DiagnosisPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: doctor.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := du.mutation.DiagnosisIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   diagnosis.DiagnosisTable,
			Columns: diagnosis.DiagnosisPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: doctor.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, du.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{diagnosis.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return 0, err
	}
	return n, nil
}

// DiagnosisUpdateOne is the builder for updating a single Diagnosis entity.
type DiagnosisUpdateOne struct {
	config
	hooks    []Hook
	mutation *DiagnosisMutation
}

// AddDiagnosiIDs adds the "diagnosis" edge to the Doctor entity by IDs.
func (duo *DiagnosisUpdateOne) AddDiagnosiIDs(ids ...int) *DiagnosisUpdateOne {
	duo.mutation.AddDiagnosiIDs(ids...)
	return duo
}

// AddDiagnosis adds the "diagnosis" edges to the Doctor entity.
func (duo *DiagnosisUpdateOne) AddDiagnosis(d ...*Doctor) *DiagnosisUpdateOne {
	ids := make([]int, len(d))
	for i := range d {
		ids[i] = d[i].ID
	}
	return duo.AddDiagnosiIDs(ids...)
}

// Mutation returns the DiagnosisMutation object of the builder.
func (duo *DiagnosisUpdateOne) Mutation() *DiagnosisMutation {
	return duo.mutation
}

// ClearDiagnosis clears all "diagnosis" edges to the Doctor entity.
func (duo *DiagnosisUpdateOne) ClearDiagnosis() *DiagnosisUpdateOne {
	duo.mutation.ClearDiagnosis()
	return duo
}

// RemoveDiagnosiIDs removes the "diagnosis" edge to Doctor entities by IDs.
func (duo *DiagnosisUpdateOne) RemoveDiagnosiIDs(ids ...int) *DiagnosisUpdateOne {
	duo.mutation.RemoveDiagnosiIDs(ids...)
	return duo
}

// RemoveDiagnosis removes "diagnosis" edges to Doctor entities.
func (duo *DiagnosisUpdateOne) RemoveDiagnosis(d ...*Doctor) *DiagnosisUpdateOne {
	ids := make([]int, len(d))
	for i := range d {
		ids[i] = d[i].ID
	}
	return duo.RemoveDiagnosiIDs(ids...)
}

// Save executes the query and returns the updated Diagnosis entity.
func (duo *DiagnosisUpdateOne) Save(ctx context.Context) (*Diagnosis, error) {
	var (
		err  error
		node *Diagnosis
	)
	if len(duo.hooks) == 0 {
		node, err = duo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*DiagnosisMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			duo.mutation = mutation
			node, err = duo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(duo.hooks) - 1; i >= 0; i-- {
			mut = duo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, duo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (duo *DiagnosisUpdateOne) SaveX(ctx context.Context) *Diagnosis {
	node, err := duo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (duo *DiagnosisUpdateOne) Exec(ctx context.Context) error {
	_, err := duo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (duo *DiagnosisUpdateOne) ExecX(ctx context.Context) {
	if err := duo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (duo *DiagnosisUpdateOne) sqlSave(ctx context.Context) (_node *Diagnosis, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   diagnosis.Table,
			Columns: diagnosis.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: diagnosis.FieldID,
			},
		},
	}
	id, ok := duo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "ID", err: fmt.Errorf("missing Diagnosis.ID for update")}
	}
	_spec.Node.ID.Value = id
	if duo.mutation.DiagnosisCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   diagnosis.DiagnosisTable,
			Columns: diagnosis.DiagnosisPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: doctor.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := duo.mutation.RemovedDiagnosisIDs(); len(nodes) > 0 && !duo.mutation.DiagnosisCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   diagnosis.DiagnosisTable,
			Columns: diagnosis.DiagnosisPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: doctor.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := duo.mutation.DiagnosisIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   diagnosis.DiagnosisTable,
			Columns: diagnosis.DiagnosisPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: doctor.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Diagnosis{config: duo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, duo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{diagnosis.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	return _node, nil
}
