// Code generated by entc, DO NOT EDIT.

package proceduretype

import (
	"github.com/facebook/ent/dialect/sql"
	"github.com/facebook/ent/dialect/sql/sqlgraph"
	"github.com/team06/app/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.ProcedureType {
	return predicate.ProcedureType(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.ProcedureType {
	return predicate.ProcedureType(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.ProcedureType {
	return predicate.ProcedureType(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.ProcedureType {
	return predicate.ProcedureType(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.ProcedureType {
	return predicate.ProcedureType(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.ProcedureType {
	return predicate.ProcedureType(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.ProcedureType {
	return predicate.ProcedureType(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.ProcedureType {
	return predicate.ProcedureType(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.ProcedureType {
	return predicate.ProcedureType(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// ProcedureType applies equality check predicate on the "ProcedureType" field. It's identical to ProcedureTypeEQ.
func ProcedureType(v string) predicate.ProcedureType {
	return predicate.ProcedureType(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldProcedureType), v))
	})
}

// ProcedureTypeEQ applies the EQ predicate on the "ProcedureType" field.
func ProcedureTypeEQ(v string) predicate.ProcedureType {
	return predicate.ProcedureType(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldProcedureType), v))
	})
}

// ProcedureTypeNEQ applies the NEQ predicate on the "ProcedureType" field.
func ProcedureTypeNEQ(v string) predicate.ProcedureType {
	return predicate.ProcedureType(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldProcedureType), v))
	})
}

// ProcedureTypeIn applies the In predicate on the "ProcedureType" field.
func ProcedureTypeIn(vs ...string) predicate.ProcedureType {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.ProcedureType(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldProcedureType), v...))
	})
}

// ProcedureTypeNotIn applies the NotIn predicate on the "ProcedureType" field.
func ProcedureTypeNotIn(vs ...string) predicate.ProcedureType {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.ProcedureType(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldProcedureType), v...))
	})
}

// ProcedureTypeGT applies the GT predicate on the "ProcedureType" field.
func ProcedureTypeGT(v string) predicate.ProcedureType {
	return predicate.ProcedureType(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldProcedureType), v))
	})
}

// ProcedureTypeGTE applies the GTE predicate on the "ProcedureType" field.
func ProcedureTypeGTE(v string) predicate.ProcedureType {
	return predicate.ProcedureType(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldProcedureType), v))
	})
}

// ProcedureTypeLT applies the LT predicate on the "ProcedureType" field.
func ProcedureTypeLT(v string) predicate.ProcedureType {
	return predicate.ProcedureType(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldProcedureType), v))
	})
}

// ProcedureTypeLTE applies the LTE predicate on the "ProcedureType" field.
func ProcedureTypeLTE(v string) predicate.ProcedureType {
	return predicate.ProcedureType(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldProcedureType), v))
	})
}

// ProcedureTypeContains applies the Contains predicate on the "ProcedureType" field.
func ProcedureTypeContains(v string) predicate.ProcedureType {
	return predicate.ProcedureType(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldProcedureType), v))
	})
}

// ProcedureTypeHasPrefix applies the HasPrefix predicate on the "ProcedureType" field.
func ProcedureTypeHasPrefix(v string) predicate.ProcedureType {
	return predicate.ProcedureType(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldProcedureType), v))
	})
}

// ProcedureTypeHasSuffix applies the HasSuffix predicate on the "ProcedureType" field.
func ProcedureTypeHasSuffix(v string) predicate.ProcedureType {
	return predicate.ProcedureType(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldProcedureType), v))
	})
}

// ProcedureTypeEqualFold applies the EqualFold predicate on the "ProcedureType" field.
func ProcedureTypeEqualFold(v string) predicate.ProcedureType {
	return predicate.ProcedureType(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldProcedureType), v))
	})
}

// ProcedureTypeContainsFold applies the ContainsFold predicate on the "ProcedureType" field.
func ProcedureTypeContainsFold(v string) predicate.ProcedureType {
	return predicate.ProcedureType(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldProcedureType), v))
	})
}

// HasProcedureToMedicalProcedure applies the HasEdge predicate on the "ProcedureToMedicalProcedure" edge.
func HasProcedureToMedicalProcedure() predicate.ProcedureType {
	return predicate.ProcedureType(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(ProcedureToMedicalProcedureTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ProcedureToMedicalProcedureTable, ProcedureToMedicalProcedureColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasProcedureToMedicalProcedureWith applies the HasEdge predicate on the "ProcedureToMedicalProcedure" edge with a given conditions (other predicates).
func HasProcedureToMedicalProcedureWith(preds ...predicate.MedicalProcedure) predicate.ProcedureType {
	return predicate.ProcedureType(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(ProcedureToMedicalProcedureInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ProcedureToMedicalProcedureTable, ProcedureToMedicalProcedureColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ProcedureType) predicate.ProcedureType {
	return predicate.ProcedureType(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ProcedureType) predicate.ProcedureType {
	return predicate.ProcedureType(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ProcedureType) predicate.ProcedureType {
	return predicate.ProcedureType(func(s *sql.Selector) {
		p(s.Not())
	})
}
